apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: oii7g6hb2-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oii7g6hb2-java-quarkus 
  name: oii7g6hb2-java-quarkus
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: oii7g6hb2-java-quarkus
    weight: 100 
